basic.showIcon(IconNames.Happy)
pins.servoWritePin(AnalogPin.P8, 0)
basic.pause(200)
basic.forever(function () {
    pins.servoWritePin(AnalogPin.P8, 0)
    basic.pause(1000)
    pins.servoWritePin(AnalogPin.P8, 45)
    basic.pause(1000)
    pins.servoWritePin(AnalogPin.P8, 90)
    basic.pause(1000)
    pins.servoWritePin(AnalogPin.P8, 135)
    basic.pause(1000)
    pins.servoWritePin(AnalogPin.P8, 180)
    basic.pause(1000)
})
